label l01_fruhlingsbeginn_end:

    $ bgi_load_base()
    $ bgi_push_dword(48)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00b48')
    $ bgi_reg_exception_handler()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '15')
    $ bgi_push_base_offset(44)
    $ bgi_push_dword(0)
    $ bgi_push_dword(4)
    $ bgi_mul()
    $ bgi_add()
    $ bgi_push_dword(0)
    $ bgi_f_0e1()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '16')
    $ bgi_push_base_offset(44)
    $ bgi_push_dword(1)
    $ bgi_push_dword(4)
    $ bgi_mul()
    $ bgi_add()
    $ bgi_push_dword(1)
    $ bgi_f_0e1()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '17')
    $ bgi_push_base_offset(44)
    $ bgi_push_dword(2)
    $ bgi_push_dword(4)
    $ bgi_mul()
    $ bgi_add()
    $ bgi_push_dword(2)
    $ bgi_f_0e1()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '18')
    $ bgi_push_base_offset(44)
    $ bgi_push_dword(3)
    $ bgi_push_dword(4)
    $ bgi_mul()
    $ bgi_add()
    $ bgi_push_dword(5)
    $ bgi_f_0e1()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '22')
    $ bgi_push_base_offset(28)
    $ bgi_push_dword(4)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '25')
    $ bgi_push_base_offset(24)
    $ bgi_push_dword(0)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '28')
    $ bgi_push_base_offset(20)
    $ bgi_push_dword(3)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '31')
    $ bgi_push_base_offset(16)
    $ bgi_push_dword(0)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '32')

label l01_fruhlingsbeginn_end_001bc:
    $ bgi_push_base_offset(16)
    $ bgi_load(2)
    $ bgi_push_base_offset(28)
    $ bgi_load(2)
    $ bgi_lt()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_002f4')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '35')
    $ bgi_push_base_offset(44)
    $ bgi_push_base_offset(16)
    $ bgi_load(2)
    $ bgi_push_dword(4)
    $ bgi_mul()
    $ bgi_add()
    $ bgi_load(2)
    $ bgi_push_base_offset(20)
    $ bgi_load(2)
    $ bgi_geq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_002a4')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '37')
    $ bgi_push_base_offset(24)
    $ bgi_push_dword(1)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '38')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_002f4')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '39')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_002a4')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_002a4:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '42')
    $ bgi_push_base_offset(16)
    $ bgi_push_base_offset(16)
    $ bgi_load(2)
    $ bgi_push_dword(1)
    $ bgi_add()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '43')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_001bc')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_002f4:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '46')
    $ bgi_push_base_offset(24)
    $ bgi_load(2)
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00940')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '49')
    $ bgi_push_base_offset(12)
    $ bgi_push_dword(0)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '50')
    $ bgi_push_base_offset(8)
    $ bgi_push_dword(0)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '51')

label l01_fruhlingsbeginn_end_00380:
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_base_offset(28)
    $ bgi_load(2)
    $ bgi_lt()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00928')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '54')
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '56')
    $ bgi_push_base_offset(4)
    $ bgi_push_dword(0)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '57')

label l01_fruhlingsbeginn_end_00404:
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_push_base_offset(28)
    $ bgi_load(2)
    $ bgi_lt()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_005c0')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '60')
    $ bgi_push_base_offset(44)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(4)
    $ bgi_mul()
    $ bgi_add()
    $ bgi_load(2)
    $ bgi_push_base_offset(44)
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_push_dword(4)
    $ bgi_mul()
    $ bgi_add()
    $ bgi_load(2)
    $ bgi_gt()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00508')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '63')
    $ bgi_push_base_offset(12)
    $ bgi_push_base_offset(12)
    $ bgi_load(2)
    $ bgi_push_dword(1)
    $ bgi_add()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '64')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00508')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00508:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '67')
    $ bgi_push_base_offset(12)
    $ bgi_load(2)
    $ bgi_push_dword(3)
    $ bgi_geq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00570')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '69')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_005c0')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '70')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00570')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00570:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '73')
    $ bgi_push_base_offset(4)
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_push_dword(1)
    $ bgi_add()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '74')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00404')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_005c0:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '77')
    $ bgi_push_base_offset(12)
    $ bgi_load(2)
    $ bgi_push_dword(3)
    $ bgi_geq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00888')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '80')
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_base_offset(48)
    $ bgi_move_arg(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '83')
    $ bgi_push_dword(0)
    $ bgi_push_base_offset(48)
    $ bgi_load(2)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_006ac')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '86')
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '88')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00858')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '91')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_006d8')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_006ac:
    $ bgi_push_dword(1)
    $ bgi_push_base_offset(48)
    $ bgi_load(2)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00728')
    $ bgi_jc(0)

label l01_fruhlingsbeginn_end_006d8:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '94')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '96')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00858')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '99')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00754')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00728:
    $ bgi_push_dword(2)
    $ bgi_push_base_offset(48)
    $ bgi_load(2)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_007a4')
    $ bgi_jc(0)

label l01_fruhlingsbeginn_end_00754:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '102')
    $ bgi_push_dword(1)
    $ bgi_push_dword(2)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '104')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00858')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '107')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_007d0')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_007a4:
    $ bgi_push_dword(3)
    $ bgi_push_base_offset(48)
    $ bgi_load(2)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00814')
    $ bgi_jc(0)

label l01_fruhlingsbeginn_end_007d0:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '110')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '112')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00858')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '115')

label l01_fruhlingsbeginn_end_00814:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '118')
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '120')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00858')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '121')

label l01_fruhlingsbeginn_end_00858:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '123')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00928')
    $ bgi_jmp()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '124')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_008b4')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00888:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '129')
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '130')

label l01_fruhlingsbeginn_end_008b4:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '133')
    $ bgi_push_base_offset(12)
    $ bgi_push_dword(0)
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '136')
    $ bgi_push_base_offset(8)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(1)
    $ bgi_add()
    $ bgi_move(2)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '137')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00380')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00928:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '138')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_0096c')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00940:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '144')
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_f_0e4()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '145')

label l01_fruhlingsbeginn_end_0096c:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '148')
    $ bgi_push_dword(0)
    $ bgi_f_0e5()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_009e0')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '150')
    $ bgi_push_string('02_Abend_rn_master')
    $ bgi_f_0f0()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '151')
    call bgi_f_0f4
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '152')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_009e0')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_009e0:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '155')
    $ bgi_push_dword(1)
    $ bgi_f_0e5()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00a54')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '157')
    $ bgi_push_string('02_Abend_pi_master')
    $ bgi_f_0f0()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '158')
    call bgi_f_0f4
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '159')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00a54')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00a54:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '162')
    $ bgi_push_dword(2)
    $ bgi_f_0e5()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00ac8')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '164')
    $ bgi_push_string('02_Abend_ze_master')
    $ bgi_f_0f0()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '165')
    call bgi_f_0f4
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '166')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00ac8')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00ac8:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '169')
    $ bgi_push_dword(5)
    $ bgi_f_0e5()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00b3c')
    $ bgi_jc(0)
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '171')
    $ bgi_push_string('02_Abend_an_master')
    $ bgi_f_0f0()
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '172')
    call bgi_f_0f4
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '173')
    $ bgi_push_offset('l01_fruhlingsbeginn_end_00b3c')
    $ bgi_jmp()

label l01_fruhlingsbeginn_end_00b3c:
    $ bgi_line('01_Fruhlingsbeginn_end.bss', '177')

label l01_fruhlingsbeginn_end_00b48:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(48)
    $ bgi_sub()
    $ bgi_store_base()
    return
