label l04_what_is_mind？_01:

    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('l04_what_is_mind？_01_01e54')
    $ bgi_reg_exception_handler()
    $ bgi_line('04_What_is_mind丠_01.bss', '24')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ic0005a')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '25')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('04_What_is_mind丠_01.bss', '27')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('04_What_is_mind丠_01.bss', '28')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('04_What_is_mind丠_01.bss', '30')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010a')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '32')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('bgm040')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('04_What_is_mind丠_01.bss', '33')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('04_What_is_mind丠_01.bss', '35')
    $ bgi_push_string('kid_000001')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '37')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「如何啊？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '39')
    $ bgi_push_string('wkd_000048')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '41')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「你指什么？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '43')
    $ bgi_push_string('kid_000002')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '45')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「我是说直哉啦直哉」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '47')
    $ bgi_push_string('wkd_000049')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '49')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「啊~是说直哉吗……似乎有很多烦恼的样子呢」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '54')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010b')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '58')
    $ bgi_push_string('kid_000003')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '60')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「我想也是呢……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '62')
    $ bgi_push_string('wkd_000050')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '64')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「为什么要把遗产统统给他？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '69')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010a')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '73')
    $ bgi_push_string('kid_000004')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '75')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「嘛，我这边也是有各种情况的啦」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '77')
    $ bgi_push_string('wkd_000051')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '79')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「各种情况吗……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '81')
    $ bgi_push_string('wkd_000052')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '83')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「说起来，草薙先生带过来的少女是谁啊？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '88')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010c')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '92')
    $ bgi_push_string('kid_000005')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '94')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「啊，你在说什么~」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '96')
    $ bgi_push_string('wkd_000053')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '98')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「算了，这不是我该说三道四的问题。尽管如此，在直哉的这个年纪，让他参与夏目家的问题，是不是有点过分呢？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '103')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010d')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '108')
    $ bgi_push_string('kid_000006')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '110')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「那是没办法的。直哉是草薙家的人啊。说到草薙家的人，就是注定要被卷入大事的」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '112')
    $ bgi_push_string('wkd_000054')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '114')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「什么样的一族啊……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '119')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010e')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '123')
    $ bgi_push_string('kid_000007')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '125')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「不管是什么样的一族，发生过什么事，你都知道的吧？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '127')
    $ bgi_push_string('wkd_000055')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '129')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「我所知甚少。只知道草薙学生拐跑了我们弓张学园所有男生的憧憬女神——水菜小姐」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '131')
    $ bgi_push_string('kid_000008')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '133')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「拐跑吗……嘛，旁人来看或许正是如此……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '135')
    $ bgi_push_string('wkd_000056')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '137')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「即使不从旁观者的视角看，那也是私奔吧？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '139')
    $ bgi_push_string('kid_000009')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '141')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是这样吗……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '143')
    $ bgi_push_string('wkd_000057')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '145')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「后来我也稍微了解了一下情况。 因为夏目家的蓝酱去弓张学园赴任当老师了呢」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '147')
    $ bgi_push_string('kid_000010')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '149')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「这样啊，说起来……蓝在弓张学园当老师呢……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '152')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010a')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '155')
    $ bgi_push_string('kid_000011')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '157')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「看来我也上岁数了呢……原本那么小的女孩现在都已经当老师了……虽然身材还是那么矮小」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '159')
    $ bgi_push_string('wkd_000058')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '161')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「那个，跟蓝老师说的话会被杀的哦。 因为她很在意身高的事」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '166')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010d')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '170')
    $ bgi_push_string('kid_000012')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '172')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「没什么好在意的。蓝啊，生得那么漂亮。虽然比较小，但对有那种兴趣爱好的人来说是是一种奖励啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '174')
    $ bgi_push_string('wkd_000059')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '176')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「那句话可是蓝老师的逆鳞啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '181')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010b')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '185')
    $ bgi_push_string('kid_000013')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '187')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是吗。嘛，反正我惹蓝生气也不是一次两次了……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '189')
    $ bgi_push_string('wkd_000060')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '191')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「是吗？ 不过最近没有吧？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '193')
    $ bgi_push_string('kid_000014')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '195')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「不不，我刚被狠狠地骂过一顿」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '197')
    $ bgi_push_string('wkd_000061')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '199')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「这样啊。你做什么了吗？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '201')
    $ bgi_push_string('kid_000015')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '203')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「不，相反。因为什么都没做所以挨骂了」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '205')
    $ bgi_push_string('wkd_000062')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '207')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「因为什么都没做？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '209')
    $ bgi_push_string('kid_000016')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '211')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「为什么在这种病恶化之前不回来呢？被狠狠地骂了一顿」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '213')
    $ bgi_push_string('wkd_000063')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '215')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「那是当然的。说实话我也是这么想的」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '220')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010a')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '224')
    $ bgi_push_string('kid_000017')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '226')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「但你不是没生气吗」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '228')
    $ bgi_push_string('wkd_000064')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '230')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「那是自然。因为草薙先生是个优秀的大人」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '232')
    $ bgi_push_string('kid_000018')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '234')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「嗯，“一个优秀的大人为什么做这种事！”她就是这么骂我的……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '239')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010e')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '242')
    $ bgi_push_string('kid_000019')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '244')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「因为她从以前开始就是个好强的姑娘啊。哭的那样伤心的话，我心里会有点痛的」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '246')
    $ bgi_push_string('wkd_000065')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '248')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「那样的话，去医院不就好了吗？从很久以前开始，身体就不舒服了吧？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '250')
    $ bgi_push_string('kid_000020')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '252')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「即便如此，我也想自己决定自己的寿命」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '254')
    $ bgi_push_string('wkd_000066')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '256')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「所以呢？你能精确地计算自己剩下的寿命吗？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '260')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010b')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '264')
    $ bgi_push_string('kid_000021')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '266')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「谁知道呢……。勉强赶上了吗？ 真是不可思议啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '268')
    $ bgi_push_string('wkd_000067')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '270')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「勉强赶上了？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '272')
    $ bgi_push_string('kid_000022')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '274')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「如果，将那个作为我的终点的话，那还是相当不错的呢」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '276')
    $ bgi_push_string('kid_000023')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '278')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「因为我在有生之年，被刻上了墓志铭啊……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '280')
    $ bgi_push_string('wkd_000068')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '282')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '284')
    $ bgi_push_string('wkd_000069')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '286')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「呼……真是的，真是个造孽的人啊。草薙先生」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '291')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010c')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '298')
    $ bgi_push_string('kid_000024')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '300')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「你说啥？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '302')
    $ bgi_push_string('wkd_000070')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '304')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「上次来的时候，我问了同样的问题，你说“稍微算错了一点”的」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '306')
    $ bgi_push_string('kid_000025')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '308')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是这样吗？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '310')
    $ bgi_push_string('wkd_000071')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '312')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「原来如此，也就是说是直哉把所有事情都解决掉了吧」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '314')
    $ bgi_push_string('kid_000026')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '316')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「谁知道呢。我不晓得。再说了，我也不知道那家伙最终会怎么处理遗产，对吧？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '318')
    $ bgi_push_string('wkd_000072')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '320')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「原来如此，嘛，虽然我不知道细节，但草薙先生心情不错啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '324')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010a')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '328')
    $ bgi_push_string('kid_000027')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '330')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是啊。相对来说」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '332')
    $ bgi_push_string('wkd_000073')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '334')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「真是，任性的人啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '339')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010d')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '342')
    $ bgi_push_string('kid_000028')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '344')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是的。我是最任性的。所以，我活得也最任性啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '346')
    $ bgi_push_string('kid_000029')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '348')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「颇为惊险有趣的人生哟」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '350')
    $ bgi_push_string('wkd_000074')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '352')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「惊险而有趣……呢。嘛，没错啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '354')
    $ bgi_push_string('kid_000030')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '356')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「今晚，我最后的晚餐。 你要听我讲述吗？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '358')
    $ bgi_push_string('wkd_000075')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '360')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「还“最后的晚餐”……料理和酒都没有」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '362')
    $ bgi_push_string('kid_000031')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '364')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「有酒哦，还有，用我的故事作为下酒菜吧」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '366')
    $ bgi_push_string('wkd_000076')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '368')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「过去的故事是下酒菜吗」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '370')
    $ bgi_push_string('kid_000032')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '372')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「啊，虽然下酒菜的量有点大？听好了哟」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '374')
    $ bgi_push_string('wkd_000077')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '376')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「草薙先生说让我去听，我怎么可能会拒绝呢？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '378')
    $ bgi_push_string('kid_000033')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '380')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「我不会强迫你的哦」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '382')
    $ bgi_push_string('wkd_000078')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '384')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「就算你不强迫我，我也不能拒绝。 那么，让我听听我那道菜是什么吧？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '386')
    $ bgi_push_string('wkd_000079')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '388')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「我也是，你死的时候可能会有点寂寞。 你的故事也许能稍微填补一下我内心的空虚」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '390')
    $ bgi_push_string('kid_000034')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '392')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是吗，那太好了。 你还记得吗？ 当我还是弓张学园的老师的时候……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '394')
    $ bgi_push_string('wkd_000080')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '396')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「嗯，我还记得。那时我正好是那个学校的学生」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '402')
    $ bgi_push_string('kid_000035')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '404')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是啊，是美术社的啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '406')
    $ bgi_push_string('wkd_000081')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '408')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「草薙先生也经常来参加社团活动吧」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '410')
    $ bgi_push_string('kid_000036')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '412')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「因为我没有地方可以去啊……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '414')
    $ bgi_push_string('kid_000037')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '416')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「话虽如此，从那时候起……水菜就很可爱啊」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '418')
    $ bgi_push_string('wkd_000082')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '420')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「确实无法反驳。她就是以美貌著称」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '422')
    $ bgi_push_string('kid_000038')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '424')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「没错，不过，如果生来不是那样的美人的话，那么不幸的事应该也不会发生吧……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '426')
    $ bgi_push_string('wkd_000083')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '428')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「……那个故事，我真的可以听吗？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '433')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010b')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '437')
    $ bgi_push_string('kid_000039')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '439')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「是啊，倒不如说，我想让你听我说。 这些，所有的东西都压在我的胸口太沉重了啊……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '441')
    $ bgi_push_string('wkd_000084')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '443')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「这不正好，对直哉说不就行了吗」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '448')
    $ bgi_push_dword(1000)
    $ bgi_push_string('evb010e')
    call bgi_f_280
    $ bgi_line('04_What_is_mind丠_01.bss', '452')
    $ bgi_push_string('kid_000040')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '454')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「另一个人会告诉直哉一切的……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '456')
    $ bgi_push_string('wkd_000085')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '458')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「另一个人？」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '461')
    $ bgi_push_string('kid_000041')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '463')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「啊，那个姑娘，最了解我和水菜的故事。总有一天，她会告诉直哉的……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '465')
    $ bgi_push_string('kid_000042')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '467')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「所以，我想让你听听……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '469')
    $ bgi_push_string('kid_000043')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '471')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「也是为了今晚能喝到最好的酒……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '473')
    $ bgi_push_string('wkd_000086')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '475')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「酒吗……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '477')
    $ bgi_push_string('kid_000044')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '479')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「啊，是一种叫幸福的美酒……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '481')
    $ bgi_push_string('wkd_000087')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '483')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('若田')
    $ bgi_push_string('「幸福……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '485')
    $ bgi_push_string('kid_000045')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '487')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「我已经活不久了。人生的晚辈哟。正因如此，我想让你听听我的故事」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '489')
    $ bgi_push_string('kid_000046')
    call bgi_f_1a9
    $ bgi_line('04_What_is_mind丠_01.bss', '491')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('健一郎')
    $ bgi_push_string('「这是为了饮用幸福而讲述的故事……」')
    $ bgi_f_140()
    $ bgi_line('04_What_is_mind丠_01.bss', '493')
    $ bgi_push_dword(0)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('04_What_is_mind丠_01.bss', '494')
    $ bgi_push_dword(4000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('map021')
    $ bgi_push_string('white')
    call bgi_f_281
    $ bgi_line('04_What_is_mind丠_01.bss', '495')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('04_What_is_mind丠_01.bss', '505')

label l04_what_is_mind？_01_01e54:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_sub()
    $ bgi_store_base()
    return
