label l05_the_happy_prince_09b:

    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('l05_the_happy_prince_09b_02054')
    $ bgi_reg_exception_handler()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '14')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ic0006a')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_09b.bss', '15')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('05_The_Happy_Prince_09b.bss', '23')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('05_The_Happy_Prince_09b.bss', '24')
    $ bgi_push_dword(1500)
    call bgi_f_110
    $ bgi_line('05_The_Happy_Prince_09b.bss', '31')
    $ bgi_push_dword(1000)
    $ bgi_push_string('bg1029a')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_09b.bss', '36')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('bgm020')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('05_The_Happy_Prince_09b.bss', '39')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「蓝你在吗！？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '42')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我在夏目宅的玄关大喊道。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '44')
    $ bgi_push_string('aid_001602')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '46')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯，直哉，怎么了？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '49')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我跑向出声的方向。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '55')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(7)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ai2000ca')
    $ bgi_push_dword(4)
    call bgi_f_2c0
    $ bgi_line('05_The_Happy_Prince_09b.bss', '58')
    $ bgi_push_string('aid_001603')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '60')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「怎么了，喊那么大声」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '63')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「我回了趟公寓……看到了大学通知书」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '65')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2011ca')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '66')
    $ bgi_push_string('aid_001604')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '68')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「诶，意思是……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '71')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯，我的第一志愿，蓝的母校」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '73')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2011aa')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '74')
    $ bgi_push_string('aid_001605')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '76')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「究、究竟如何？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '79')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「还没看呢。我想在蓝面前打开它」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '81')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2007ba')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '82')
    $ bgi_push_string('aid_001606')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '84')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「诶，这样吗？我、我有点紧张呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '87')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嘛，我还是有点自信的……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '90')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「毕竟那之后蓝片刻不离地教我功课呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '92')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2001ba')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '93')
    $ bgi_push_string('aid_001607')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '95')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯，我擅长的科目和你擅长的科目是错开的真是太好了呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '98')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「那么我开了哦」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '100')
    $ bgi_push_string('aid_001608')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '102')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '105')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(4)
    call bgi_f_2c8
    $ bgi_line('05_The_Happy_Prince_09b.bss', '109')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我打开装有通知书的信封。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '112')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '115')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　里面装着一大堆 文件。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '118')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「什么啊这是？全是文件……最关键的合格通知呢？……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '121')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(7)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ai2000aa')
    $ bgi_push_dword(4)
    call bgi_f_2c0
    $ bgi_line('05_The_Happy_Prince_09b.bss', '124')
    $ bgi_push_string('aid_001609')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '126')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「文件？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '128')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2011aa')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '129')
    $ bgi_push_string('aid_001610')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '131')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「啊，说起来……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '134')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「怎么了？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '136')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2001ca')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '137')
    $ bgi_push_string('aid_001611')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '139')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「既然送来的是这个信封……那么结果已经显而易见了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '141')
    $ bgi_push_string('aid_001612')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '143')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「要是没有的合格的话，就没有必要送来这么大的信封了……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '146')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？真的吗？这就是合格通知吗？啊——」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '149')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(4)
    call bgi_f_2c8
    $ bgi_line('05_The_Happy_Prince_09b.bss', '153')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我发现一张纸。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '156')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　上面写着“合格通知”。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '159')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「真得诶！」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '165')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(7)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ai2003ab_l')
    $ bgi_push_dword(4)
    call bgi_f_2c0
    $ bgi_line('05_The_Happy_Prince_09b.bss', '168')
    $ bgi_push_string('aid_001613')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '170')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「干得好！直哉！」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '173')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯！」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '176')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(4)
    call bgi_f_2c8
    $ bgi_line('05_The_Happy_Prince_09b.bss', '177')
    $ bgi_push_dword(128)
    $ bgi_push_string('se3356')
    call bgi_f_1a1
    $ bgi_line('05_The_Happy_Prince_09b.bss', '181')
    $ bgi_push_dword(0)
    $ bgi_push_dword(10)
    $ bgi_push_dword(2)
    $ bgi_push_dword(0)
    $ bgi_push_dword(5)
    $ bgi_push_dword(240)
    call bgi_f_232
    $ bgi_line('05_The_Happy_Prince_09b.bss', '184')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　蓝抱住我。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '187')
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    call bgi_f_233
    $ bgi_line('05_The_Happy_Prince_09b.bss', '190')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(7)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ai2001aa_l')
    $ bgi_push_dword(4)
    call bgi_f_2c0
    $ bgi_line('05_The_Happy_Prince_09b.bss', '194')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「是蓝就读过的教育学部。但是学科不同」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '196')
    $ bgi_push_string('aid_001614')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '198')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「是呢。但是从这里去上学会很辛苦哦」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '201')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「说什么呢。蓝不也是从这个家出发的吗？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '203')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2001ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '204')
    $ bgi_push_string('aid_001615')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '206')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯，是呢。不过我从没想到直哉会以老师为目标」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '209')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「或许吧……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '212')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯……或许是这样呢……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '215')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「不过，如果我不把某个梦想作为目标的话，是无法前进的」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '218')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「失去的话……就再依靠一个新的梦想」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '220')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2002ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '221')
    $ bgi_push_string('aid_001616')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '223')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「不要说什么“依靠梦想”这种话。确立一个目标，卖出第一步，你这不做的挺好的嘛」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '225')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2003ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '226')
    $ bgi_push_string('aid_001617')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '228')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「我没想到那么没干劲的你居然会用功到如此地步」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '231')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「原本我就是个一旦集中便成事有余的人。只是持续力不够罢了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '233')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2001aa_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '234')
    $ bgi_push_string('aid_001618')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '236')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「不过你的集中力还真是惊人呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '239')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯，这下我也是个堂堂正正的大学生了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '242')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「话说蓝，那个约定你还记得吗？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '244')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2001ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '245')
    $ bgi_push_string('aid_001619')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '247')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「约定？是说什么呢……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '250')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「别装傻。不是说好了，我成为大学生之后，就要认真和我交往吗」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '252')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2007ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '253')
    $ bgi_push_string('aid_001620')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '255')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「我知道。可是这样好吗？我和你的岁数差了好多，马上就会变成老太婆的哦」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '258')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「还“老太婆”……等你长了阴毛再说那种话吧！」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '260')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2004ab_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '261')
    $ bgi_push_string('aid_001621')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '263')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「呜哇！你居然提这个！做的时候你明明都没说！却要在这种时候提及吗！」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '266')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯，虽说做的时候我就想说了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '268')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2014ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '269')
    $ bgi_push_string('aid_001622')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '271')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「你就不懂什么叫体贴吗」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '274')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「我这个性格蓝最清楚不过了吧」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '276')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2016ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '277')
    $ bgi_push_string('aid_001623')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '279')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「既然你有这个自觉，那还不赶快改正」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '282')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「是呢，如果蓝讨厌这样的话，我就改正」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '284')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2009ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '285')
    $ bgi_push_string('aid_001624')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '287')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「真是的，你就不能说点像样的话吗」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '290')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「话说，蓝……虽说是约定」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '292')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2001aa_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '293')
    $ bgi_push_string('aid_001625')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '295')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「这不是什么约定」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '297')
    $ bgi_push_string('aid_001626')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '299')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「我会一种陪伴在你身旁，不管是以何种形式」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '301')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2003ca_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '302')
    $ bgi_push_string('aid_001627')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '304')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「我这样起誓了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '306')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2001ca_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '307')
    $ bgi_push_string('aid_001628')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '309')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「所以我会一直在你身旁」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '311')
    $ bgi_push_string('aid_001629')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '313')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「为了使你永远不再悲伤……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '316')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「我已经不会再悲伤了……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '318')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2100aa_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '319')
    $ bgi_push_string('aid_001630')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '321')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「直哉……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '324')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(4)
    call bgi_f_2c8
    $ bgi_line('05_The_Happy_Prince_09b.bss', '328')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　蓝再度抱住我。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '331')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　那个胸口倍感温暖。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '334')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(7)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ai2001aa_l')
    $ bgi_push_dword(4)
    call bgi_f_2c0
    $ bgi_line('05_The_Happy_Prince_09b.bss', '337')
    $ bgi_push_string('aid_001631')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '339')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「没有悲伤了呢……必须要和悲伤说再见……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '342')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '344')
    $ bgi_push_string('aid_001632')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '346')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「樱花还会盛开」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '349')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '351')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('ai2001ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '352')
    $ bgi_push_string('aid_001633')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '354')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「今年我们两人去看樱花吧……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '356')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('ai2003ba_l')
    $ bgi_push_dword(4)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_09b.bss', '357')
    $ bgi_push_string('aid_001634')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_09b.bss', '359')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「想必今年的樱花一定很漂亮吧」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '362')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(4)
    call bgi_f_2c8
    $ bgi_line('05_The_Happy_Prince_09b.bss', '366')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　蓝望向不知名的远方。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '369')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　她的视线前端，浮着一片小小的云朵。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_09b.bss', '371')
    $ bgi_push_dword(0)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('05_The_Happy_Prince_09b.bss', '373')
    $ bgi_push_dword(2000)
    call bgi_f_153
    $ bgi_line('05_The_Happy_Prince_09b.bss', '377')
    $ bgi_push_dword(3000)
    call bgi_f_288
    $ bgi_line('05_The_Happy_Prince_09b.bss', '379')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('05_The_Happy_Prince_09b.bss', '381')

label l05_the_happy_prince_09b_02054:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_sub()
    $ bgi_store_base()
    return
