label l05_the_happy_prince_06:

    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('l05_the_happy_prince_06_0233c')
    $ bgi_reg_exception_handler()
    $ bgi_line('05_The_Happy_Prince_06.bss', '14')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ic0006a')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_06.bss', '15')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('05_The_Happy_Prince_06.bss', '23')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('05_The_Happy_Prince_06.bss', '24')
    $ bgi_push_dword(1500)
    call bgi_f_110
    $ bgi_line('05_The_Happy_Prince_06.bss', '31')
    $ bgi_push_dword(1000)
    $ bgi_push_string('sp0048a')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_06.bss', '36')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('bgm001')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('05_The_Happy_Prince_06.bss', '39')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　那之后我一心一意地画着画。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '42')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我使尽浑身解数埋首于画布。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '45')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　有时用左手。有时靠弹簧装置辅助左手，不拘泥于做法，为了完成最棒的作品，使尽一切手段。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '49')
    $ bgi_push_dword(3000)
    $ bgi_push_string('sp0048b')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_06.bss', '54')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　画了几张。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '57')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　然而都不能令我满意。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '60')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我现在所能做的事情。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '63')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我现在能画出的画。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '66')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我不断深入。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '70')
    $ bgi_push_dword(3000)
    $ bgi_push_string('sp0048c')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_06.bss', '75')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　某天晚上。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '78')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　那家伙又来了。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '82')
    $ bgi_push_dword(1000)
    $ bgi_push_string('bg1033e')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_06.bss', '83')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_dword(8)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('kn1003aa')
    $ bgi_push_dword(14)
    call bgi_f_2c0
    $ bgi_line('05_The_Happy_Prince_06.bss', '86')
    $ bgi_push_string('knd_000648')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '88')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「精神振作了呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '91')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嘛，是呢……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '94')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「你来做什么？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '96')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '97')
    $ bgi_push_string('knd_000649')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '99')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「也没什么特别的理由啦。只是在想着……你大概正在画吧……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '102')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「这样啊……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '105')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「话说，你这算是非法闯入吧」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '107')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1015aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '108')
    $ bgi_push_string('knd_000650')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '110')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「这种常识我才不会管呢……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '113')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「干嘛那么拽啊……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '115')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1003aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '116')
    $ bgi_push_string('knd_000651')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '118')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「因为我就是那种人啊」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '121')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「居然还不要脸地认了……真是服了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '123')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '124')
    $ bgi_push_string('knd_000652')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '126')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「又重新跑起来了呢……草薙君」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '129')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「谁知道呢。我只是现在在画。仅此而已」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '131')
    $ bgi_push_string('knd_000653')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '133')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「哼~嗯，这样啊……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '136')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「长山不参加穆尔展吗？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '138')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1011aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '139')
    $ bgi_push_string('knd_000654')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '141')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「我吗？开玩笑，我怎么会」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '144')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「是吗？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '146')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(500)
    $ bgi_push_string('kn1004aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '147')
    $ bgi_push_string('knd_000655')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '149')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「我很清楚自己的实力。这种纪念考试一样的东西我最讨厌了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '152')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「你这一句话把弓张学园历代所有美术部员都给否定了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '154')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '155')
    $ bgi_push_string('knd_000656')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '157')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「是啊。但我就是讨厌。再说了，普通学生怎么可能能够在那个穆尔展上获奖」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '160')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「也是呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '162')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1004aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '163')
    $ bgi_push_string('knd_000657')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '165')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「我只会在能确实获胜的时候去摘桂冠」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '167')
    $ bgi_push_string('knd_000658')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '169')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「并且为了赢，我会不计任何手段」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '171')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1000aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '172')
    $ bgi_push_string('knd_000659')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '174')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「所有说，草薙君……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '176')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1004aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '177')
    $ bgi_push_string('knd_000660')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '179')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「既然要做，就给我赢。不要让我幻灭」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '182')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「我也是这么希望的」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '185')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「不过，我没法做保证。我只会尽我所能」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '188')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「所以，谢谢你，长山」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '190')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '193')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　长山轻柔一笑。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '195')
    $ bgi_push_string('knd_000661')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '197')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「我曾经，只喜欢自己的极彩色世界」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '199')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1000aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '200')
    $ bgi_push_string('knd_000662')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '202')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「你的出现使我失去了那个世界。但是，就算你不在了，丢失的色彩也没法取回了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '204')
    $ bgi_push_string('knd_000663')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '206')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「若是能够打倒完全复活的你，或许我就又可以看到我的世界」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '208')
    $ bgi_push_string('knd_000664')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '210')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「现在我依旧是这么想的」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '212')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '213')
    $ bgi_push_string('knd_000665')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '215')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「所以，你并不需要感谢我」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '217')
    $ bgi_push_string('knd_000666')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '219')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「因为我总有一天会打倒你的」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '221')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1000aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '222')
    $ bgi_push_string('knd_000667')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '224')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「我是为了那个才帮你的」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '227')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯，我就祝愿你能够重拾那个美妙的绘画世界吧」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '229')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1004aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '230')
    $ bgi_push_string('knd_000668')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '232')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「真是的，完全没把我视作威胁呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '235')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「干嘛啦，我只是说了真心话而已啊」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '237')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1008aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '238')
    $ bgi_push_string('knd_000669')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '240')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「哪怕只有一点点也好，我也想让你尝尝焦躁的味道」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '243')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「是吗。你要真想如此，就画出超棒的画给我看吧」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '245')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1004aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '246')
    $ bgi_push_string('knd_000670')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '248')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「就算你不说我也会画的。然后最终我会将你们全部打倒，独自站上顶点」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '251')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「加油吧。我期待着」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '253')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1009aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '254')
    $ bgi_push_string('knd_000671')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '256')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「答得真是轻松……嘛，这也没办法，毕竟现在的我……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '258')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1008aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '259')
    $ bgi_push_string('knd_000672')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '261')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「以我现在的实力，考上艺大太难了，只能勉强上预备校……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '264')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嘛，那个确实很难考」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '266')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1000aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '267')
    $ bgi_push_string('knd_000673')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '269')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「但是，我会过关的」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '272')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「若是以艺术家为目标的话，那也算是个妥当的目标」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '274')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1008aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '275')
    $ bgi_push_string('knd_000674')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '277')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「是呢。嘛，是呢……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '279')
    $ bgi_push_string('knd_000675')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '281')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '283')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '284')
    $ bgi_push_string('knd_000676')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '286')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「那么我也差不多该回去了吧……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '289')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「老实说你到底是来干嘛的啊」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '291')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1011aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '292')
    $ bgi_push_string('knd_000677')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '294')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「啊，那幅画，你不要了吗？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '298')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　长山指着被我画完就扔的一堆画布。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '301')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「啊，你说那个？啊，嗯，不要了。因为不喜欢所以我打算涂白后重新当做画布来使」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '303')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1002aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '304')
    $ bgi_push_string('knd_000678')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '306')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「对了，帮忙的报酬我还没收呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '309')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「什么！事到如今还惦记着那三万日元吗！？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '311')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1015aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '312')
    $ bgi_push_string('knd_000679')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '314')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「三万日元或许也不错呢……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '317')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「但、但不是说好了那只是胜负成立不了的场合才给的吗，姑且打成平手了」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '319')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '320')
    $ bgi_push_string('knd_000680')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '322')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「那么，就把那张画给我吧」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '325')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？画？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '327')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1003aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '328')
    $ bgi_push_string('knd_000681')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '330')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「是的。那幅能看见月亮的城镇的风景画……能给我吗？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '333')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「可以是可以，不过你要我的画有什么用？」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '335')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '336')
    $ bgi_push_string('knd_000682')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '338')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「也没什么别的理由。只是想从你手中拿到月亮」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '341')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　长山拿起我的画。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '343')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1000aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '344')
    $ bgi_push_string('knd_000683')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '346')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「这画真不错呢……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '349')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「是吗？我觉得不行」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '351')
    $ bgi_push_string('knd_000684')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '353')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「或许吧……但仍旧是幅好画……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '356')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「什么意思啊……」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '358')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1001aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '359')
    $ bgi_push_string('knd_000685')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '361')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「关于画画的事情……你也有不懂的地方呢」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '363')
    $ bgi_push_string('knd_000686')
    call bgi_f_1a9
    $ bgi_line('05_The_Happy_Prince_06.bss', '365')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('香奈')
    $ bgi_push_string('「比起那个，既然你觉得它不行，说明你在画更加棒的画吧」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '368')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「这是当然」')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '370')
    $ bgi_push_dword(256)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    $ bgi_push_dword(300)
    $ bgi_push_string('kn1003aa')
    $ bgi_push_dword(14)
    call bgi_f_2c6
    $ bgi_line('05_The_Happy_Prince_06.bss', '373')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　长山香奈笑了。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '378')
    $ bgi_push_dword(1000)
    $ bgi_push_string('sp0048c')
    call bgi_f_280
    $ bgi_line('05_The_Happy_Prince_06.bss', '383')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　之后我才注意到，那幅画画的是从弓张学园的泳池看到的风景。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '386')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　暑假最后的那天，那里所见的风景非常美丽，我便拍了照片。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '389')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　虽然照片里是新月，却不知不觉画成了满月……')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '392')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　满月……说起来，吹和我对决的那晚也是满月呢……')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '397')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('05_The_Happy_Prince_06.bss', '402')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　那之后，我继续画着画。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '405')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　要画出比我曾画过的画都要漂亮的画。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '408')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　不停的挥笔，直到最后一秒。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '411')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　大概圭也是同样吧。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '414')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我想他也会画到最后一刻。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '417')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我想，最终完成画的那一刻应该就是。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '420')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　穆尔公募展的截稿日。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '423')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我终于画好了自己的作品。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '426')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　草薙直哉的回归作。')
    $ bgi_f_140()
    $ bgi_line('05_The_Happy_Prince_06.bss', '429')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('05_The_Happy_Prince_06.bss', '431')
    $ bgi_push_dword(2000)
    call bgi_f_153
    $ bgi_line('05_The_Happy_Prince_06.bss', '433')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('05_The_Happy_Prince_06.bss', '435')
    $ bgi_push_dword(0)
    call bgi_f_184
    $ bgi_line('05_The_Happy_Prince_06.bss', '440')

label l05_the_happy_prince_06_0233c:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_sub()
    $ bgi_store_base()
    return
