label l06_ⅵ_08:

    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('l06_ⅵ_08_03c24')
    $ bgi_reg_exception_handler()
    $ bgi_line('06_嘫_08.bss', '16')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ic0007b')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '17')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '18')
    $ bgi_push_dword(2000)
    call bgi_f_288
    $ bgi_line('06_嘫_08.bss', '19')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '26')
    $ bgi_push_dword(300)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('map004')
    $ bgi_push_string('white')
    call bgi_f_281
    $ bgi_line('06_嘫_08.bss', '29')
    $ bgi_push_dword(0)
    $ bgi_push_dword(5)
    $ bgi_push_dword(4)
    $ bgi_push_dword(15)
    $ bgi_push_dword(15)
    $ bgi_push_dword(240)
    call bgi_f_232
    $ bgi_line('06_嘫_08.bss', '30')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「！？　蓝！」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '31')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    call bgi_f_233
    $ bgi_line('06_嘫_08.bss', '37')
    $ bgi_push_dword(1000)
    $ bgi_push_string('bg1025a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '38')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('bgm001')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('06_嘫_08.bss', '42')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「蓝？　蓝你在吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '45')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '48')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　一如既往的房间，一如既往的光景。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '51')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　理所当然一般，没有人回应我的呼喊。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '54')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「哈，我在做什么呢……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '57')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「啧……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '60')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我躺下身子。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '63')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　居然梦见蓝回来了……')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '66')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我到底是有多软弱啊……')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '69')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「不过话说回来……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '72')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我好像说了一大堆让人面红耳赤的话啊。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '75')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　那是个梦真是万幸。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '78')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「那么接下来……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '81')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我站了起来。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '84')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　精神状态良好。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '87')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　大概昨天吐过了之后，体内的酒都吐干净了吧。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '90')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「今天的课是从第三节开始……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '93')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「不用急应该也没关系吧？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '98')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('lse0820')
    $ bgi_push_dword(0)
    call bgi_f_190
    $ bgi_line('06_嘫_08.bss', '102')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　正当我准备换衣服时，手机响起。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '105')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「这个号码是什么情况？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '108')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　没见过的号码。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '111')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我的手机几乎不会有人打过来。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '114')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　更别说是没见过的号码了。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '117')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「是打错的吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '121')
    call bgi_f_151
    $ bgi_line('06_嘫_08.bss', '123')
    $ bgi_push_dword(128)
    $ bgi_push_string('se3434')
    call bgi_f_1a1
    $ bgi_line('06_嘫_08.bss', '124')
    $ bgi_push_dword(0)
    call bgi_f_194
    $ bgi_line('06_嘫_08.bss', '125')
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    call bgi_f_1a4
    $ bgi_line('06_嘫_08.bss', '129')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「你好……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '132')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？啊，是」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '135')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '138')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '141')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「呃，是辞退通知吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '144')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('06_嘫_08.bss', '146')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('06_嘫_08.bss', '147')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '149')
    $ bgi_push_dword(1000)
    $ bgi_push_string('sp0010a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '150')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('bgm022')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('06_嘫_08.bss', '151')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '152')
    $ bgi_push_dword(500)
    call bgi_f_152
    $ bgi_line('06_嘫_08.bss', '156')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「果然事情不妙啊……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '159')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　登着梦浮坂，感觉脚步沉重。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '162')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「本来村山理事就看我不爽了，又让他丢了面子……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '165')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「啊，世道已经如此不景气了，现在工作也要丢了吗……难受」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '168')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　老实说，我并不是认为没有解雇的可能性。只是井上理事这次长脸了，所以我还在想应该能继续平安无事地混下去。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '171')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「真不想面对啊……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '174')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　正门越来越近。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '178')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('06_嘫_08.bss', '179')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '181')
    $ bgi_push_dword(1000)
    $ bgi_push_string('bg1001a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '182')
    $ bgi_push_dword(500)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '186')
    $ bgi_push_dword(128)
    $ bgi_push_string('se2924')
    call bgi_f_1a1
    $ bgi_line('06_嘫_08.bss', '187')
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    call bgi_f_1a4
    $ bgi_line('06_嘫_08.bss', '192')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「我是草薙直哉」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '195')
    $ bgi_push_string('htd_000397')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '197')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「啊，进来吧……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '203')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('06_嘫_08.bss', '205')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '211')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev7009a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '216')
    $ bgi_push_string('htd_000398')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '218')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「前天正是辛苦你了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '221')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「啊，不，该怎么说呢……确实没能事先取得校长的许可……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '228')
    $ bgi_push_string('htd_000399')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '230')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「为什么要我许可呢？井上理事不是已经许可了吗。我当然也会收到联络」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '236')
    $ bgi_push_string('htd_000400')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '238')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「更何况，既然弗里曼氏都行动了，我不觉得什么都不会发生。据说他的嗅觉可不是盖的」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '241')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「哈啊，既然是这样……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '248')
    $ bgi_push_string('htd_000401')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '250')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「话虽如此，村山理事可是火冒三丈呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '253')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？呃，果然……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '259')
    $ bgi_push_string('htd_000402')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '261')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「毕竟自己辛苦计划的一切，全部变成了井上理事的风头」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '267')
    $ bgi_push_string('htd_000403')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '269')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「“给我炒了那个外聘的小子！”他气势汹汹地说道」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '272')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「那个……所以今天叫我来是……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '278')
    $ bgi_push_string('htd_000404')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '280')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「啊~，跟电话里说的一样，是辞退通知」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '283')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「即是说……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '285')
    $ bgi_push_string('htd_000405')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '287')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「本来的话，三月份之前就必须要告知你了，但是中途因为那个涂鸦事件，所以没空谈这个」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '290')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「三月份之前吗？也就是说传言是真的……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '296')
    $ bgi_push_string('htd_000406')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '298')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「传言？传言说什么？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '301')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「啊，不，没什么」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '307')
    $ bgi_push_string('htd_000407')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '309')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「嘛，毕竟说好了呢。而且早在很久以前就已经决定好了……来年开始草薙直哉就不再是外聘讲师，而是正规雇员」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '312')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '319')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　完全出乎意料的话语。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '322')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　从外聘转正式。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '325')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我成正式职工了？')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '332')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？教员？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '334')
    $ bgi_push_string('htd_000408')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '336')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「你当外聘讲师的时候接受了私立学校适性检测，然后合格了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '338')
    $ bgi_push_string('htd_000409')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '340')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「虽然最终还要根据你本人意志，但是这之后生活应该会变得更加安定吧。我觉得这个提案应该不坏吧？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '343')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「何止不坏，简直棒极了！可、可是为什么是现在？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '346')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「我也没有拿出过什么成果……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '352')
    $ bgi_push_string('htd_000410')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '354')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「就算你没有实绩，也不可能让美术教师的位置一直空着吧。就算弓张再怎么中落，好歹也是个艺术家辈出的学校」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '356')
    $ bgi_push_string('htd_000411')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '358')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「至今为止一直没有美术教师确实是个问题」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '365')
    $ bgi_push_string('htd_000412')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '367')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「话虽如此，这事情也成之不易呢。村山理事对你恨之入骨，一提到这个，就表示强烈反对……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '370')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「唔……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '376')
    $ bgi_push_string('htd_000413')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '378')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「话虽如此，约定就是约定。不可能只看理事的脸色行事」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '381')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「呃……那个，约定是指？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '387')
    $ bgi_push_string('htd_000414')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '389')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「我能做的说明只有这些。希望你可以当即回复我」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '392')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「我当然是OK啦」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '398')
    $ bgi_push_string('htd_000415')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '400')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「是吗，既然如此那你就在这些文件上签名吧。本来的话这些事情早就该办妥了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '403')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「呃，好的……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '408')
    $ bgi_push_dword(1000)
    $ bgi_push_string('bg1014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '411')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我在校长的桌上签好了文件。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '416')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev7009a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '418')
    $ bgi_push_string('htd_000416')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '420')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「那么，从来年开始，你就是美术教师了。有着和通常教师一样的各种权利」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '426')
    $ bgi_push_string('htd_000417')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '428')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「怎样？不想让弓张学园的美术部复活吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '431')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「不，那种事情要让学生干吧？教师又做不到」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '437')
    $ bgi_push_string('htd_000418')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '439')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('校长')
    $ bgi_push_string('「或许吧。嘛，行吧，总之今后也请多多关照了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '442')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「是，这边才是，还望您多多关照」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '449')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我低头鞠躬。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '454')
    $ bgi_push_dword(1000)
    call bgi_f_153
    $ bgi_line('06_嘫_08.bss', '455')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('06_嘫_08.bss', '456')
    $ bgi_push_dword(700)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '457')
    $ bgi_push_dword(1000)
    call bgi_f_288
    $ bgi_line('06_嘫_08.bss', '459')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '462')
    $ bgi_push_dword(1000)
    $ bgi_push_string('bg1003wa')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '463')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '464')
    $ bgi_push_dword(1000)
    call bgi_f_152
    $ bgi_line('06_嘫_08.bss', '468')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我走下梦浮坂。两旁的樱树已长出花苞。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '471')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「今年开花貌似会很早呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '474')
    $ bgi_push_string('aid_001676')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '476')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('？？？')
    $ bgi_push_string('「是呢。今年的樱花会是怎样的呢？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '479')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '482')
    $ bgi_push_dword(1000)
    call bgi_f_153
    $ bgi_line('06_嘫_08.bss', '486')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('bgm035')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('06_嘫_08.bss', '487')
    $ bgi_push_dword(4000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '489')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '491')
    $ bgi_push_dword(1000)
    call bgi_f_152
    $ bgi_line('06_嘫_08.bss', '495')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「蓝……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '500')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014b')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '504')
    $ bgi_push_string('aid_001677')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '506')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯，我是蓝。是蓝老师哦」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '508')
    $ bgi_push_string('aid_001678')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '510')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「直哉要回去了吗？我也是。撒，回去吧」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '513')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「“回去”是指……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '515')
    $ bgi_push_string('aid_001679')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '517')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「当然是回我们的家啊」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '520')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「回夏目宅吗？可、可蓝不是在到很远的姐妹学校赴任去了吗……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '525')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014c')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '529')
    $ bgi_push_string('aid_001680')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '531')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「呼，那个校长还是一如既往地省略说明了呢。直哉什么都没听说吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '534')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「也就被告知我被正式雇佣了……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '539')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014d')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '543')
    $ bgi_push_string('aid_001681')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '545')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「真是的，只说结论吗。鸟谷校长还真是坏心眼呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '548')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「到底什么情况啊」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '550')
    $ bgi_push_string('aid_001682')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '552')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「首先，我并不是去姐妹学校赴任。我是被召唤到那儿去的」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '555')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「召唤过去？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '557')
    $ bgi_push_string('aid_001683')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '559')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯，那里发生了点问题，所以作为能解决它的人才，我被借调过去了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '562')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「为什么要叫蓝去？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '567')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014e')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '571')
    $ bgi_push_string('aid_001684')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '573')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「因为是女校的问题，所以像我这种年轻的女性教师是必要的。嘛，尽是些麻烦事呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '575')
    $ bgi_push_string('aid_001685')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '577')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「因为被塞了棘手的工作，所以鸟谷校长和我做了约定。只要我能解决这个问题，就让直哉转正」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '579')
    $ bgi_push_string('aid_001686')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '581')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「为此让你接受了私立学校适性检查」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '584')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「确实，明明没有被正规采用，却接受了私立学校适性检查」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '587')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「也就是说，那是和蓝做的约定吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '589')
    $ bgi_push_string('aid_001687')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '591')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「是啊。一直当外聘也太过分了。弓张是多重所有制，所以喜欢削减人力成本。若田桑也因此吃了很多苦呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '596')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '600')
    $ bgi_push_string('aid_001688')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '602')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「我至今都未能为直哉做过什么，却反倒一直接受着你的帮助……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '604')
    $ bgi_push_string('aid_001689')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '606')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「雫的事情……现在提这个已经不要紧了吧，是你把她从中村家里救出来的吧？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '608')
    $ bgi_push_string('aid_001690')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '610')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「通过放弃巨额遗产……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '613')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「不，那只是装逼装过头了……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '615')
    $ bgi_push_string('aid_001691')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '617')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「圭感到很不甘呢。本来的话，应该由身为家人的我们自己去拯救雫，但是草薙的人又一次帮助了我们……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '619')
    $ bgi_push_string('aid_001692')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '621')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「对圭来说，草薙家的人就像英雄一样呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '623')
    $ bgi_push_string('aid_001693')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '625')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「你是竞争对手。然后健一郎先生是憧憬对象」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '628')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「圭憧憬他？圭和健一郎见过吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '630')
    $ bgi_push_string('aid_001694')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '632')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「没有，但是他的爱车，和我的马赫III同样都曾是健一郎先生坐过的东西」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '635')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「诶？是这样吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '637')
    $ bgi_push_string('aid_001695')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '639')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「马赫III是在国内，而Vespa是在纽约使用的摩托」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '641')
    $ bgi_push_string('aid_001696')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '643')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「健一郎回到国内的时候把它交给了我……但是圭偏要自己坐」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '645')
    $ bgi_push_string('aid_001697')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '647')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「虽然马赫III是部麻烦的摩托，但是Vespa也很麻烦。因为太危险所以我曾表示反对……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '649')
    $ bgi_push_string('aid_001698')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '651')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「但是，圭心里一直憧憬着健一郎先生吧。虽然表面上装成没那回事……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '654')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「马赫III的事情我知道，但没想到连那部Vespa居然也是健一郎的东西……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '656')
    $ bgi_push_string('aid_001699')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '658')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「现在好像由你开着呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '661')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯，因为太老旧，保养起来很麻烦呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '666')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014f')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '670')
    $ bgi_push_string('aid_001700')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '672')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「圭也是这么抱怨的」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '677')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '681')
    $ bgi_push_string('aid_001701')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '683')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「因为他喜欢着草薙家的人……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '685')
    $ bgi_push_string('aid_001702')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '687')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「不，不光圭是这样。雫也是，然后我也是……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '692')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014b')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '696')
    $ bgi_push_string('aid_001703')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '698')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「最喜欢草薙直哉和草薙健一郎了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '703')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '707')
    $ bgi_push_string('aid_001704')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '709')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「虽然跟至今为止受到的恩情比起来太过渺小，但这次我让校长做了绝对的保证」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '712')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「呃，是这样吗……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '714')
    $ bgi_push_string('aid_001705')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '716')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯，虽然在那忙活了一整年，但也算是有了价值」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '719')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「原来是这种理由啊……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '721')
    $ bgi_push_string('aid_001706')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '723')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「就是因为这个理由才会离开这里」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '726')
    $ bgi_push_dword(4268)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ev5014b')
    $ bgi_push_dword(30)
    call bgi_f_2c0
    $ bgi_line('06_嘫_08.bss', '728')
    $ bgi_push_string('aid_001707')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '730')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「然后，回来了。我回来了，直哉」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '733')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「欢迎回家，蓝」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '735')
    $ bgi_push_string('aid_001708')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '737')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「呵呵呵……总觉得有点难为情呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '740')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「或许吧……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '743')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '746')
    $ bgi_push_string('aid_001709')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '748')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「那么，差不多也该回去了吧，相互之间一定积了很多话想说」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '751')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '753')
    $ bgi_push_string('aid_001710')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '755')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「夏目家吗……仅仅只是一年没见，却有种十分怀念的感觉」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '758')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「就连我也一直有种离开了家的感觉」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '760')
    $ bgi_push_string('aid_001711')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '762')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「这话说的还真是令人开心呢。是感到寂寞了吗？」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '765')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「昨晚……你看到那个了吧。如果那不是梦的话……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '767')
    $ bgi_push_string('aid_001712')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '769')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嗯，你哭了呢」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '772')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「那、那是因为我吐了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '774')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014b')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '777')
    $ bgi_push_string('aid_001713')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '779')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「是是」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '782')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '785')
    $ bgi_push_string('aid_001714')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '787')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「有什么不可呢。能看到那样的直哉，大概也就只有我了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '790')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「这、这是当然啦！倒不如说这种状况本身就极难发生！」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '792')
    $ bgi_push_string('aid_001715')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '794')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「你总是憋了太多，直哉」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '796')
    $ bgi_push_string('aid_001716')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '798')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「多哭一点也行。多向我撒娇一点也行」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '801')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「呃，这……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '803')
    $ bgi_push_string('aid_001717')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '805')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「虽然已经不能说有家族的样子了，但即便如此，我们已经是留在夏目家的最后两个人了」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '810')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014g')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '814')
    $ bgi_push_string('aid_001718')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '816')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「我希望你以后不再独自一人硬撑了……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '818')
    $ bgi_push_string('aid_001719')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '820')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「哪怕是我，也是可以成为你的依靠的」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '823')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「蓝……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '828')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014b')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '832')
    $ bgi_push_string('aid_001720')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '834')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「在你娶到老婆前，我会认真当好你的姐姐，守护着你」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '837')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「虽然依旧是一个幼小的姐姐……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '842')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014h')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '846')
    $ bgi_push_string('aid_001721')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '848')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「你说啥！」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '853')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '857')
    $ bgi_push_string('aid_001722')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '859')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「虽然我想这么说……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '862')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014i')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '865')
    $ bgi_push_string('aid_001723')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '867')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「嘛，一旦到了这个年纪，被当成年轻人反而令人高兴呢……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '869')
    $ bgi_push_string('aid_001724')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '871')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「总之，直到你结婚，我都会一直照看着你。作为教师，亦作为前辈」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '874')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '879')
    $ bgi_push_dword(1000)
    $ bgi_push_string('ev5014a')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '883')
    $ bgi_push_string('aid_001725')
    call bgi_f_1a9
    $ bgi_line('06_嘫_08.bss', '885')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝')
    $ bgi_push_string('「那么，回去吧，回我们的家……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '888')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_string('直哉')
    $ bgi_push_string('「嗯……」')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '890')
    $ bgi_push_dword(2000)
    call bgi_f_153
    $ bgi_line('06_嘫_08.bss', '893')
    $ bgi_push_dword(3000)
    $ bgi_push_string('ev5014j')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '895')
    $ bgi_push_dword(3000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '897')
    $ bgi_push_dword(2000)
    call bgi_f_152
    $ bgi_line('06_嘫_08.bss', '901')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　樱花含苞欲放。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '904')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　虽然春天的脚步声已经临近，但离春天到来尚有一段时日。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '907')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我们两人走下梦浮坂。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '910')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　整个弓张一览无余。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '913')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　太阳尚在高处。\n但是再过数小时也将下山。\n')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '914')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('届时，城镇将会通火通明。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '917')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　弓张的夜景犹如落樱一样美丽。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '920')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　大概是因为，那一片一片的花瓣之中，一盏一盏的灯火之中，包含着每个人的不同生活吧。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '923')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　单片花瓣也很美丽。但果然，被无数的花瓣包围才更加美丽吧。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '926')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　人与人之间的因果交流之灯。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '929')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　无数的人之间的因果点亮了灯光。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '932')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我们的家也是那样的灯火的其中之一。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '935')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　夏目宅。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '938')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　那里有着各种各样的人的思念，以及各种各样的人的过去。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '941')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　夏目琴子。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '944')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　草薙健一郎。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '947')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　草薙水菜。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '950')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　夏目雫。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '953')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　夏目圭。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '956')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　以及 夏目蓝。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '959')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　不，还有草薙直哉。我也是那其中的一人。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '962')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　那间宅子里发生了各种各样的事情。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '965')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　有着数之不尽的回忆。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '968')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　有好的， 有坏的。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '971')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　塞满了那个场所。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '974')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　所以，我们要回到那里。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '977')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我们并非是停下了脚步。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '980')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　并非是驻足不前。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '983')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　在这里，在这个地方，我走在我的人生道路上。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '986')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我一边想着那样的事情，一边望着天空。蓝说“我们正好好地走着”。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '989')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　从今往后，我们将并肩而行。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '992')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　缓缓地，两人一起……')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '995')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　向着无限延伸的道路。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '998')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　我们缓缓迈出了脚步。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '1001')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('　看着那样的我，\n')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '1002')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('蓝微微一笑。')
    $ bgi_f_140()
    $ bgi_line('06_嘫_08.bss', '1008')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    call bgi_f_145
    $ bgi_line('06_嘫_08.bss', '1009')
    $ bgi_push_string('这时，似乎能隐约听见<r サクラノ詩>樱花在唱歌</r>。')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(18)
    $ bgi_push_string('MessageCenter')
    $ bgi_f_01c()
    $ bgi_line('06_嘫_08.bss', '1010')
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    call bgi_f_145
    $ bgi_line('06_嘫_08.bss', '1017')
    $ bgi_push_dword(2000)
    call bgi_f_153
    $ bgi_line('06_嘫_08.bss', '1019')
    $ bgi_push_dword(3000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '1021')
    $ bgi_push_dword(0)
    $ bgi_push_dword(8000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('06_嘫_08.bss', '1023')
    $ bgi_push_dword(3000)
    $ bgi_push_string('white')
    call bgi_f_280
    $ bgi_line('06_嘫_08.bss', '1025')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('06_嘫_08.bss', '1029')

label l06_ⅵ_08_03c24:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_sub()
    $ bgi_store_base()
    return
