label led05:

    $ bgi_load_base()
    $ bgi_push_dword(12)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('led05_01240')
    $ bgi_reg_exception_handler()
    $ bgi_line('ED05.bss', '13')
    call bgi_f_151
    $ bgi_line('ED05.bss', '17')
    $ bgi_push_base_offset(8)
    $ bgi_push_dword(235000)
    $ bgi_move(2)
    $ bgi_line('ED05.bss', '24')
    $ bgi_push_dword(0)
    call bgi_f_120
    $ bgi_line('ED05.bss', '25')
    $ bgi_push_dword(0)
    call bgi_f_121
    $ bgi_line('ED05.bss', '26')
    $ bgi_push_dword(0)
    call bgi_f_122
    $ bgi_line('ED05.bss', '27')
    $ bgi_push_dword(0)
    call bgi_f_123
    $ bgi_line('ED05.bss', '28')
    $ bgi_push_dword(1)
    call bgi_f_124
    $ bgi_line('ED05.bss', '34')
    $ bgi_push_dword(125)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('led05_00160')
    $ bgi_jc(0)
    $ bgi_line('ED05.bss', '36')
    $ bgi_push_dword(1)
    call bgi_f_114
    $ bgi_line('ED05.bss', '37')
    $ bgi_push_dword(1)
    call bgi_f_120
    $ bgi_line('ED05.bss', '38')
    $ bgi_push_dword(1)
    call bgi_f_121
    $ bgi_line('ED05.bss', '39')
    $ bgi_push_offset('led05_00160')
    $ bgi_jmp()

label led05_00160:
    $ bgi_line('ED05.bss', '43')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('ED05.bss', '45')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('ED05_DMF')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('ED05.bss', '46')
    $ bgi_push_dword(0)
    call bgi_f_112
    $ bgi_line('ED05.bss', '47')
    $ bgi_push_base_offset(4)
    $ bgi_f_101()
    $ bgi_move(2)
    $ bgi_line('ED05.bss', '50')
    $ bgi_push_dword(2000)
    call bgi_f_288
    $ bgi_line('ED05.bss', '77')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(11)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1268)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_BG_Black_l2')
    $ bgi_push_dword(11)
    call bgi_f_300
    $ bgi_line('ED05.bss', '78')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(10)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_string('.11')
    $ bgi_push_string('ED05_END01')
    $ bgi_push_dword(12)
    call bgi_f_300
    $ bgi_line('ED05.bss', '79')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(11)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1561)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_BG_Black_l2')
    $ bgi_push_dword(13)
    call bgi_f_300
    $ bgi_line('ED05.bss', '80')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(10)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_string('.13')
    $ bgi_push_string('ED05_END02')
    $ bgi_push_dword(14)
    call bgi_f_300
    $ bgi_line('ED05.bss', '81')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(11)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(975)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_BG_Black_l2')
    $ bgi_push_dword(15)
    call bgi_f_300
    $ bgi_line('ED05.bss', '82')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(10)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_string('.15')
    $ bgi_push_string('ED05_END03')
    $ bgi_push_dword(16)
    call bgi_f_300
    $ bgi_line('ED05.bss', '87')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(296)
    $ bgi_push_dword(920)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED05_staff_past')
    $ bgi_push_dword(30)
    call bgi_f_300
    $ bgi_line('ED05.bss', '94')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(20)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(427)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_BG_Black_l2')
    $ bgi_push_dword(1)
    call bgi_f_300
    $ bgi_line('ED05.bss', '96')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(11)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_BG_Black_r2')
    $ bgi_push_dword(10)
    call bgi_f_300
    $ bgi_line('ED05.bss', '97')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(10)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_string('.10')
    $ bgi_push_string('ED05_Start01')
    $ bgi_push_dword(2)
    call bgi_f_300
    $ bgi_line('ED05.bss', '98')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(3)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1630)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1)
    call bgi_f_308
    $ bgi_line('ED05.bss', '99')
    $ bgi_push_dword(1500)
    call bgi_f_110
    $ bgi_line('ED05.bss', '102')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(2)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_string('.10')
    $ bgi_push_string('ED05_BG')
    $ bgi_push_dword(0)
    call bgi_f_300
    $ bgi_line('ED05.bss', '103')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(600)
    $ bgi_push_dword(10)
    call bgi_f_308
    $ bgi_line('ED05.bss', '105')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('ED05.bss', '107')
    $ bgi_push_dword(0)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(5600)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(360)
    $ bgi_add()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    call bgi_f_308
    $ bgi_line('ED05.bss', '108')
    $ bgi_push_dword(0)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(15000)
    $ bgi_sub()
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(5350)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(920)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(30)
    call bgi_f_308
    $ bgi_line('ED05.bss', '115')
    $ bgi_f_12c()
    $ bgi_bool_zero()
    $ bgi_push_offset('led05_00c54')
    $ bgi_jc(0)
    $ bgi_line('ED05.bss', '120')

label led05_00b80:
    $ bgi_f_101()
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_sub()
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_lt()
    $ bgi_push_offset('led05_00c3c')
    $ bgi_jc(0)
    $ bgi_line('ED05.bss', '122')
    $ bgi_f_12c()
    $ bgi_push_offset('led05_00c0c')
    $ bgi_jc(0)
    $ bgi_line('ED05.bss', '122')
    $ bgi_push_offset('led05_00c3c')
    $ bgi_jmp()
    $ bgi_line('ED05.bss', '122')
    $ bgi_push_offset('led05_00c0c')
    $ bgi_jmp()

label led05_00c0c:
    $ bgi_line('ED05.bss', '123')
    $ bgi_push_dword(500)
    call bgi_f_110
    $ bgi_line('ED05.bss', '124')
    $ bgi_push_offset('led05_00b80')
    $ bgi_jmp()

label led05_00c3c:
    $ bgi_line('ED05.bss', '125')
    $ bgi_push_offset('led05_00c54')
    $ bgi_jmp()

label led05_00c54:
    $ bgi_line('ED05.bss', '128')
    $ bgi_f_101()
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_sub()
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(11000)
    $ bgi_sub()
    $ bgi_geq()
    $ bgi_push_offset('led05_01090')
    $ bgi_jc(0)
    $ bgi_line('ED05.bss', '138')
    $ bgi_push_dword(1)
    $ bgi_push_dword(2000)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(914)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_last_logo1')
    $ bgi_push_dword(30)
    call bgi_f_300
    $ bgi_line('ED05.bss', '139')
    $ bgi_push_dword(500)
    call bgi_f_110
    $ bgi_line('ED05.bss', '140')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(914)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_last_logo2')
    $ bgi_push_dword(29)
    call bgi_f_300
    $ bgi_line('ED05.bss', '141')
    $ bgi_push_dword(2500)
    call bgi_f_110
    $ bgi_line('ED05.bss', '143')
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    call bgi_f_31f
    $ bgi_line('ED05.bss', '146')
    $ bgi_push_dword(0)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(30)
    call bgi_f_306
    $ bgi_line('ED05.bss', '147')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(29)
    call bgi_f_306
    $ bgi_line('ED05.bss', '150')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(566)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(11)
    call bgi_f_308
    $ bgi_line('ED05.bss', '151')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('ED05.bss', '152')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(1163)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(13)
    call bgi_f_308
    $ bgi_line('ED05.bss', '153')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('ED05.bss', '154')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(568)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(15)
    call bgi_f_308
    $ bgi_line('ED05.bss', '155')
    $ bgi_push_dword(5000)
    call bgi_f_110
    $ bgi_line('ED05.bss', '157')
    $ bgi_push_dword(6000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('map006')
    call bgi_f_289
    $ bgi_line('ED05.bss', '159')
    $ bgi_push_offset('led05_0119c')
    $ bgi_jmp()

label led05_01090:
    $ bgi_line('ED05.bss', '162')
    $ bgi_push_dword(0)
    $ bgi_push_dword(4000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('ED05.bss', '163')
    $ bgi_push_dword(1)
    $ bgi_push_dword(4000)
    $ bgi_push_dword(30)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('White')
    $ bgi_push_dword(31)
    call bgi_f_300
    $ bgi_line('ED05.bss', '164')
    $ bgi_push_dword(3000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('map023')
    call bgi_f_289
    $ bgi_line('ED05.bss', '165')

label led05_0119c:
    $ bgi_line('ED05.bss', '172')
    $ bgi_push_dword(1)
    call bgi_f_120
    $ bgi_line('ED05.bss', '173')
    $ bgi_push_dword(1)
    call bgi_f_121
    $ bgi_line('ED05.bss', '175')
    $ bgi_push_dword(1)
    call bgi_f_122
    $ bgi_line('ED05.bss', '176')
    $ bgi_push_dword(1)
    call bgi_f_123
    $ bgi_line('ED05.bss', '178')
    $ bgi_push_dword(0)
    call bgi_f_114
    $ bgi_line('ED05.bss', '182')
    $ bgi_push_dword(1)
    $ bgi_push_dword(125)
    $ bgi_f_0e6()
    $ bgi_line('ED05.bss', '186')

label led05_01240:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(12)
    $ bgi_sub()
    $ bgi_store_base()
    return
