label led06:

    $ bgi_load_base()
    $ bgi_push_dword(12)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('led06_00a48')
    $ bgi_reg_exception_handler()
    $ bgi_line('ED06.bss', '14')
    $ bgi_push_dword(1)
    $ bgi_push_string('white')
    call bgi_f_280
    $ bgi_line('ED06.bss', '18')
    $ bgi_push_base_offset(8)
    $ bgi_push_dword(205000)
    $ bgi_move(2)
    $ bgi_line('ED06.bss', '24')
    $ bgi_push_dword(0)
    call bgi_f_120
    $ bgi_line('ED06.bss', '25')
    $ bgi_push_dword(0)
    call bgi_f_121
    $ bgi_line('ED06.bss', '26')
    $ bgi_push_dword(0)
    call bgi_f_122
    $ bgi_line('ED06.bss', '27')
    $ bgi_push_dword(0)
    call bgi_f_123
    $ bgi_line('ED06.bss', '28')
    $ bgi_push_dword(1)
    call bgi_f_124
    $ bgi_line('ED06.bss', '34')
    $ bgi_push_dword(126)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('led06_00170')
    $ bgi_jc(0)
    $ bgi_line('ED06.bss', '36')
    $ bgi_push_dword(1)
    call bgi_f_114
    $ bgi_line('ED06.bss', '37')
    $ bgi_push_dword(1)
    call bgi_f_120
    $ bgi_line('ED06.bss', '38')
    $ bgi_push_dword(1)
    call bgi_f_121
    $ bgi_line('ED06.bss', '39')
    $ bgi_push_offset('led06_00170')
    $ bgi_jmp()

label led06_00170:
    $ bgi_line('ED06.bss', '43')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('ED06.bss', '45')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('ED06_ari')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('ED06.bss', '46')
    $ bgi_push_dword(0)
    call bgi_f_112
    $ bgi_line('ED06.bss', '47')
    $ bgi_push_base_offset(4)
    $ bgi_f_101()
    $ bgi_move(2)
    $ bgi_line('ED06.bss', '49')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('ED06.bss', '67')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(305)
    $ bgi_push_dword(916)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED06_staff_rinkaku')
    $ bgi_push_dword(30)
    call bgi_f_300
    $ bgi_line('ED06.bss', '69')
    $ bgi_push_dword(0)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(5000)
    $ bgi_sub()
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(5275)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(916)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(30)
    call bgi_f_308
    $ bgi_line('ED06.bss', '70')
    $ bgi_push_dword(3000)
    call bgi_f_110
    $ bgi_line('ED06.bss', '71')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(20)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_BG_White_r2')
    $ bgi_push_dword(1)
    call bgi_f_300
    $ bgi_line('ED06.bss', '72')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(5600)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(360)
    $ bgi_add()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED06_BG80')
    $ bgi_push_dword(0)
    call bgi_f_300
    $ bgi_line('ED06.bss', '74')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(1)
    call bgi_f_308
    $ bgi_line('ED06.bss', '75')
    $ bgi_push_dword(1500)
    call bgi_f_110
    $ bgi_line('ED06.bss', '76')
    $ bgi_push_dword(0)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(380)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    call bgi_f_308
    $ bgi_line('ED06.bss', '81')
    $ bgi_f_12c()
    $ bgi_bool_zero()
    $ bgi_push_offset('led06_006ac')
    $ bgi_jc(0)
    $ bgi_line('ED06.bss', '86')

label led06_005d8:
    $ bgi_f_101()
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_sub()
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_lt()
    $ bgi_push_offset('led06_00694')
    $ bgi_jc(0)
    $ bgi_line('ED06.bss', '88')
    $ bgi_f_12c()
    $ bgi_push_offset('led06_00664')
    $ bgi_jc(0)
    $ bgi_line('ED06.bss', '88')
    $ bgi_push_offset('led06_00694')
    $ bgi_jmp()
    $ bgi_line('ED06.bss', '88')
    $ bgi_push_offset('led06_00664')
    $ bgi_jmp()

label led06_00664:
    $ bgi_line('ED06.bss', '89')
    $ bgi_push_dword(500)
    call bgi_f_110
    $ bgi_line('ED06.bss', '90')
    $ bgi_push_offset('led06_005d8')
    $ bgi_jmp()

label led06_00694:
    $ bgi_line('ED06.bss', '91')
    $ bgi_push_offset('led06_006ac')
    $ bgi_jmp()

label led06_006ac:
    $ bgi_line('ED06.bss', '94')
    $ bgi_f_101()
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_sub()
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(12000)
    $ bgi_sub()
    $ bgi_geq()
    $ bgi_push_offset('led06_00898')
    $ bgi_jc(0)
    $ bgi_line('ED06.bss', '104')
    $ bgi_push_dword(1)
    $ bgi_push_dword(2000)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(914)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_last_logo1-b')
    $ bgi_push_dword(30)
    call bgi_f_300
    $ bgi_line('ED06.bss', '105')
    $ bgi_push_dword(500)
    call bgi_f_110
    $ bgi_line('ED06.bss', '106')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(914)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_last_logo2')
    $ bgi_push_dword(29)
    call bgi_f_300
    $ bgi_line('ED06.bss', '107')
    $ bgi_push_dword(2500)
    call bgi_f_110
    $ bgi_line('ED06.bss', '109')
    $ bgi_push_offset('led06_008cc')
    $ bgi_jmp()

label led06_00898:
    $ bgi_line('ED06.bss', '112')
    $ bgi_push_dword(0)
    $ bgi_push_dword(4000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('ED06.bss', '113')

label led06_008cc:
    $ bgi_line('ED06.bss', '115')
    $ bgi_push_dword(1)
    $ bgi_push_dword(4000)
    $ bgi_push_dword(30)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('White')
    $ bgi_push_dword(31)
    call bgi_f_300
    $ bgi_line('ED06.bss', '117')
    $ bgi_push_dword(3000)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('map023')
    call bgi_f_289
    $ bgi_line('ED06.bss', '121')
    $ bgi_push_dword(1)
    call bgi_f_120
    $ bgi_line('ED06.bss', '122')
    $ bgi_push_dword(1)
    call bgi_f_121
    $ bgi_line('ED06.bss', '124')
    $ bgi_push_dword(1)
    call bgi_f_122
    $ bgi_line('ED06.bss', '125')
    $ bgi_push_dword(1)
    call bgi_f_123
    $ bgi_line('ED06.bss', '127')
    $ bgi_push_dword(0)
    call bgi_f_114
    $ bgi_line('ED06.bss', '131')
    $ bgi_push_dword(1)
    $ bgi_push_dword(126)
    $ bgi_f_0e6()
    $ bgi_line('ED06.bss', '135')

label led06_00a48:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(12)
    $ bgi_sub()
    $ bgi_store_base()
    return
