label led07:

    $ bgi_load_base()
    $ bgi_push_dword(12)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('led07_00f9c')
    $ bgi_reg_exception_handler()
    $ bgi_line('ED07.bss', '13')
    call bgi_f_151
    $ bgi_line('ED07.bss', '17')
    $ bgi_push_base_offset(8)
    $ bgi_push_dword(210000)
    $ bgi_move(2)
    $ bgi_line('ED07.bss', '23')
    $ bgi_push_dword(0)
    call bgi_f_120
    $ bgi_line('ED07.bss', '24')
    $ bgi_push_dword(0)
    call bgi_f_121
    $ bgi_line('ED07.bss', '25')
    $ bgi_push_dword(0)
    call bgi_f_122
    $ bgi_line('ED07.bss', '26')
    $ bgi_push_dword(0)
    call bgi_f_123
    $ bgi_line('ED07.bss', '27')
    $ bgi_push_dword(1)
    call bgi_f_124
    $ bgi_line('ED07.bss', '33')
    $ bgi_push_dword(127)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('led07_00160')
    $ bgi_jc(0)
    $ bgi_line('ED07.bss', '35')
    $ bgi_push_dword(1)
    call bgi_f_114
    $ bgi_line('ED07.bss', '36')
    $ bgi_push_dword(1)
    call bgi_f_120
    $ bgi_line('ED07.bss', '37')
    $ bgi_push_dword(1)
    call bgi_f_121
    $ bgi_line('ED07.bss', '38')
    $ bgi_push_offset('led07_00160')
    $ bgi_jmp()

label led07_00160:
    $ bgi_line('ED07.bss', '42')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('ED07.bss', '44')
    $ bgi_push_dword(0)
    $ bgi_push_dword(128)
    $ bgi_push_string('ED07_sakura')
    $ bgi_push_dword(0)
    call bgi_f_180
    $ bgi_line('ED07.bss', '45')
    $ bgi_push_dword(0)
    call bgi_f_112
    $ bgi_line('ED07.bss', '46')
    $ bgi_push_base_offset(4)
    $ bgi_f_101()
    $ bgi_move(2)
    $ bgi_line('ED07.bss', '48')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('ED07.bss', '51')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(30)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(438)
    $ bgi_push_dword(1)
    $ bgi_sar()
    $ bgi_push_dword(800)
    $ bgi_push_dword(1)
    $ bgi_sar()
    $ bgi_push_dword(0)
    $ bgi_push_dword(50)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('logo_sakuuta1')
    $ bgi_push_dword(20)
    call bgi_f_300
    $ bgi_line('ED07.bss', '52')
    $ bgi_push_dword(1000)
    call bgi_f_110
    $ bgi_line('ED07.bss', '53')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(30)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(438)
    $ bgi_push_dword(1)
    $ bgi_sar()
    $ bgi_push_dword(800)
    $ bgi_push_dword(1)
    $ bgi_sar()
    $ bgi_push_dword(0)
    $ bgi_push_dword(50)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('logo_sakuuta2')
    $ bgi_push_dword(21)
    call bgi_f_300
    $ bgi_line('ED07.bss', '54')
    $ bgi_push_dword(2000)
    call bgi_f_110
    $ bgi_line('ED07.bss', '57')
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(11100)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED07_staff_sakura2')
    $ bgi_push_dword(30)
    call bgi_f_300
    $ bgi_line('ED07.bss', '58')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(20)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('white')
    $ bgi_push_dword(10)
    call bgi_f_300
    $ bgi_line('ED07.bss', '59')
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(3840)
    $ bgi_sub()
    $ bgi_push_dword(1280)
    $ bgi_add()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED07_BG')
    $ bgi_push_dword(0)
    call bgi_f_300
    $ bgi_line('ED07.bss', '62')
    $ bgi_push_dword(0)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(10000)
    $ bgi_sub()
    $ bgi_push_dword(9000)
    $ bgi_sub()
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    call bgi_f_308
    $ bgi_line('ED07.bss', '63')
    $ bgi_push_dword(0)
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(5000)
    $ bgi_sub()
    $ bgi_push_dword(9000)
    $ bgi_sub()
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(232)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(30)
    call bgi_f_308
    $ bgi_line('ED07.bss', '65')
    $ bgi_push_dword(0)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(10)
    call bgi_f_306
    $ bgi_line('ED07.bss', '66')
    $ bgi_push_dword(0)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(20)
    call bgi_f_306
    $ bgi_line('ED07.bss', '67')
    $ bgi_push_dword(0)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(21)
    call bgi_f_306
    $ bgi_line('ED07.bss', '70')
    $ bgi_f_12c()
    $ bgi_bool_zero()
    $ bgi_push_offset('led07_0084c')
    $ bgi_jc(0)
    $ bgi_line('ED07.bss', '75')

label led07_00778:
    $ bgi_f_101()
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_sub()
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_lt()
    $ bgi_push_offset('led07_00834')
    $ bgi_jc(0)
    $ bgi_line('ED07.bss', '77')
    $ bgi_f_12c()
    $ bgi_push_offset('led07_00804')
    $ bgi_jc(0)
    $ bgi_line('ED07.bss', '77')
    $ bgi_push_offset('led07_00834')
    $ bgi_jmp()
    $ bgi_line('ED07.bss', '77')
    $ bgi_push_offset('led07_00804')
    $ bgi_jmp()

label led07_00804:
    $ bgi_line('ED07.bss', '78')
    $ bgi_push_dword(500)
    call bgi_f_110
    $ bgi_line('ED07.bss', '79')
    $ bgi_push_offset('led07_00778')
    $ bgi_jmp()

label led07_00834:
    $ bgi_line('ED07.bss', '80')
    $ bgi_push_offset('led07_0084c')
    $ bgi_jmp()

label led07_0084c:
    $ bgi_line('ED07.bss', '83')
    $ bgi_f_101()
    $ bgi_push_base_offset(4)
    $ bgi_load(2)
    $ bgi_sub()
    $ bgi_push_base_offset(8)
    $ bgi_load(2)
    $ bgi_push_dword(11000)
    $ bgi_sub()
    $ bgi_geq()
    $ bgi_push_offset('led07_00be8')
    $ bgi_jc(0)
    $ bgi_line('ED07.bss', '87')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(30)
    call bgi_f_306
    $ bgi_line('ED07.bss', '89')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(640)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ED07_Last')
    $ bgi_push_dword(10)
    call bgi_f_300
    $ bgi_line('ED07.bss', '90')
    $ bgi_push_dword(3000)
    call bgi_f_110
    $ bgi_line('ED07.bss', '91')
    $ bgi_push_dword(1)
    $ bgi_push_dword(2000)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(321)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(94)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_last_logo_F')
    $ bgi_push_dword(30)
    call bgi_f_300
    $ bgi_line('ED07.bss', '92')
    $ bgi_push_dword(500)
    call bgi_f_110
    $ bgi_line('ED07.bss', '93')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(25)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(382)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(90)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('ED_last_logo2')
    $ bgi_push_dword(29)
    call bgi_f_300
    $ bgi_line('ED07.bss', '94')
    $ bgi_push_dword(3000)
    call bgi_f_110
    $ bgi_line('ED07.bss', '95')
    $ bgi_push_dword(0)
    $ bgi_push_dword(2000)
    $ bgi_push_dword(30)
    call bgi_f_306
    $ bgi_line('ED07.bss', '96')
    $ bgi_push_dword(1)
    $ bgi_push_dword(2000)
    $ bgi_push_dword(29)
    call bgi_f_306
    $ bgi_line('ED07.bss', '98')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(30)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(640)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ED07_Fin')
    $ bgi_push_dword(11)
    call bgi_f_300
    $ bgi_line('ED07.bss', '102')
    $ bgi_push_offset('led07_00cac')
    $ bgi_jmp()

label led07_00be8:
    $ bgi_line('ED07.bss', '105')
    $ bgi_push_dword(0)
    $ bgi_push_dword(4000)
    $ bgi_push_dword(0)
    call bgi_f_185
    $ bgi_line('ED07.bss', '106')
    $ bgi_push_dword(1)
    $ bgi_push_dword(5000)
    $ bgi_push_dword(30)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(640)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_string('ED07_Fin')
    $ bgi_push_dword(11)
    call bgi_f_300
    $ bgi_line('ED07.bss', '107')

label led07_00cac:
    $ bgi_line('ED07.bss', '112')
    $ bgi_push_dword(1)
    call bgi_f_120
    $ bgi_line('ED07.bss', '113')
    $ bgi_push_dword(1)
    call bgi_f_121
    $ bgi_line('ED07.bss', '115')
    $ bgi_push_dword(1)
    call bgi_f_122
    $ bgi_line('ED07.bss', '116')
    $ bgi_push_dword(1)
    call bgi_f_123
    $ bgi_line('ED07.bss', '118')
    $ bgi_push_dword(0)
    call bgi_f_114
    $ bgi_line('ED07.bss', '122')
    $ bgi_push_string('WaitForInputEx')
    $ bgi_f_01c()
    $ bgi_line('ED07.bss', '124')
    $ bgi_push_dword(0)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(40)
    $ bgi_push_dword(128)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(133)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_dword(3)
    $ bgi_push_string('data02504.arc')
    $ bgi_push_dword(0)
    call bgi_f_301
    $ bgi_line('ED07.bss', '125')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(39)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('White')
    $ bgi_push_dword(1)
    call bgi_f_300
    $ bgi_line('ED07.bss', '126')
    $ bgi_push_dword(2500)
    call bgi_f_110
    $ bgi_line('ED07.bss', '130')
    $ bgi_push_dword(1)
    $ bgi_push_dword(3000)
    $ bgi_push_dword(50)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(1)
    $ bgi_push_dword(1)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(0)
    $ bgi_push_dword(360)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(640)
    $ bgi_push_dword(-1)
    $ bgi_mul()
    $ bgi_push_dword(0)
    $ bgi_push_string('black')
    $ bgi_push_dword(2)
    call bgi_f_300
    $ bgi_line('ED07.bss', '133')
    $ bgi_push_dword(1)
    $ bgi_push_dword(127)
    $ bgi_f_0e6()
    $ bgi_line('ED07.bss', '137')

label led07_00f9c:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(12)
    $ bgi_sub()
    $ bgi_store_base()
    return
