label lmainforroutev:

    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('lmainforroutev_002c0')
    $ bgi_reg_exception_handler()
    $ bgi_line('MainForRouteV.bss', '15')
    $ bgi_push_dword(1)
    call bgi_f_122
    $ bgi_line('MainForRouteV.bss', '16')
    $ bgi_push_dword(1)
    call bgi_f_123
    $ bgi_line('MainForRouteV.bss', '64')
    $ bgi_push_string('05_The_Happy_Prince_01')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '65')
    $ bgi_push_string('05_The_Happy_Prince_02')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '66')
    $ bgi_push_string('05_The_Happy_Prince_03')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '67')
    $ bgi_push_string('05_The_Happy_Prince_04')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '68')
    $ bgi_push_string('05_The_Happy_Prince_05')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '69')
    $ bgi_push_string('05_The_Happy_Prince_06')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '70')
    $ bgi_push_string('05_The_Happy_Prince_07')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '74')
    $ bgi_push_dword(4)
    $ bgi_f_0e5()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_offset('lmainforroutev_00248')
    $ bgi_jc(0)
    $ bgi_line('MainForRouteV.bss', '76')
    $ bgi_push_string('05_The_Happy_Prince_08b')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '77')
    $ bgi_push_string('05_The_Happy_Prince_09b')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '80')
    $ bgi_push_dword(1)
    $ bgi_push_dword(4)
    $ bgi_f_0e6()
    $ bgi_line('MainForRouteV.bss', '83')
    $ bgi_push_dword(3)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_dword(4)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_bool_and()
    $ bgi_push_dword(230)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_bool_and()
    $ bgi_push_offset('lmainforroutev_00220')
    $ bgi_jc(0)
    $ bgi_line('MainForRouteV.bss', '85')
    $ bgi_push_dword(1)
    $ bgi_push_dword(80)
    $ bgi_f_0e6()
    $ bgi_line('MainForRouteV.bss', '86')
    $ bgi_push_offset('lmainforroutev_00220')
    $ bgi_jmp()

label lmainforroutev_00220:
    $ bgi_line('MainForRouteV.bss', '88')
    call bgi_f_0f4
    $ bgi_line('MainForRouteV.bss', '89')
    $ bgi_push_offset('lmainforroutev_002b4')
    $ bgi_jmp()

label lmainforroutev_00248:
    $ bgi_line('MainForRouteV.bss', '94')
    $ bgi_push_string('05_The_Happy_Prince_08')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '97')
    $ bgi_push_string('ED06')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteV.bss', '100')
    $ bgi_push_dword(1)
    $ bgi_push_dword(70)
    $ bgi_f_0e6()
    $ bgi_line('MainForRouteV.bss', '101')
    call bgi_f_0f4
    $ bgi_line('MainForRouteV.bss', '102')

label lmainforroutev_002b4:
    $ bgi_line('MainForRouteV.bss', '104')

label lmainforroutev_002c0:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_sub()
    $ bgi_store_base()
    return
