label lmainforroutevi:

    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_add()
    $ bgi_store_base()
    $ bgi_push_offset('lmainforroutevi_00228')
    $ bgi_reg_exception_handler()
    $ bgi_line('MainForRouteVI.bss', '16')
    $ bgi_push_dword(1)
    call bgi_f_122
    $ bgi_line('MainForRouteVI.bss', '17')
    $ bgi_push_dword(1)
    call bgi_f_123
    $ bgi_line('MainForRouteVI.bss', '20')
    $ bgi_push_string('06_Ⅵ_01')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '21')
    $ bgi_push_string('06_Ⅵ_02')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '22')
    $ bgi_push_string('06_Ⅵ_03')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '23')
    $ bgi_push_string('06_Ⅵ_04')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '24')
    $ bgi_push_string('06_Ⅵ_05')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '25')
    $ bgi_push_string('06_Ⅵ_06')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '26')
    $ bgi_push_string('06_Ⅵ_07')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '27')
    $ bgi_push_string('06_Ⅵ_08')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '30')
    $ bgi_push_string('ED07')
    $ bgi_f_0f0()
    $ bgi_line('MainForRouteVI.bss', '33')
    $ bgi_push_dword(1)
    $ bgi_push_dword(230)
    $ bgi_f_0e6()
    $ bgi_line('MainForRouteVI.bss', '36')
    $ bgi_push_dword(1)
    $ bgi_push_dword(90)
    $ bgi_f_0e6()
    $ bgi_line('MainForRouteVI.bss', '39')
    $ bgi_push_dword(3)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_push_dword(4)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_bool_and()
    $ bgi_push_dword(230)
    $ bgi_f_0e7()
    $ bgi_push_dword(1)
    $ bgi_eq()
    $ bgi_bool_and()
    $ bgi_push_offset('lmainforroutevi_0020c')
    $ bgi_jc(0)
    $ bgi_line('MainForRouteVI.bss', '41')
    $ bgi_push_dword(1)
    $ bgi_push_dword(80)
    $ bgi_f_0e6()
    $ bgi_line('MainForRouteVI.bss', '42')
    $ bgi_push_offset('lmainforroutevi_0020c')
    $ bgi_jmp()

label lmainforroutevi_0020c:
    $ bgi_line('MainForRouteVI.bss', '44')
    call bgi_f_0f4
    $ bgi_line('MainForRouteVI.bss', '48')

label lmainforroutevi_00228:
    $ bgi_unreg_exception_handler()
    $ bgi_load_base()
    $ bgi_push_dword(4)
    $ bgi_sub()
    $ bgi_store_base()
    return
